// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2O_J8DbEXtBKWxlCxNwx8_HlNSf7kMCA',
    appId: '1:621895935361:web:a72f25238e273e6524b480',
    messagingSenderId: '621895935361',
    projectId: 'stockapp-9c34c',
    authDomain: 'stockapp-9c34c.firebaseapp.com',
    storageBucket: 'stockapp-9c34c.firebasestorage.app',
    measurementId: 'G-RBHBPFMCP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQbmWkVc5jCXzt2I3ZcBQUWS0p0S876NE',
    appId: '1:621895935361:android:1a303fda3b13b90e24b480',
    messagingSenderId: '621895935361',
    projectId: 'stockapp-9c34c',
    storageBucket: 'stockapp-9c34c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8s3mTLrJYNbPanI2GU4LmIMMf9grvjxo',
    appId: '1:621895935361:ios:dfca22ed1083620724b480',
    messagingSenderId: '621895935361',
    projectId: 'stockapp-9c34c',
    storageBucket: 'stockapp-9c34c.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );
}
